extends:
  - airbnb-base
  - prettier

plugins:
  - import
  - jest
  - prettier

env:
  jest/globals: true

rules:
  prettier/prettier: ["error"]
  jest/no-disabled-tests:
    - warn
  jest/no-focused-tests:
    - error

globals:
  container: true
