extends:
    - airbnb-base

plugins:
    - import
    - jest

env:
    jest/globals: true

rules:
    linebreak-style: unix
    no-use-before-define: off
    no-multiple-empty-lines:
        - max: 1
        - maxEOF: 0
    padding-line-between-statements:
        - error
        - blankLine: always
        - prev: const
        - next: return

    jest/no-disabled-tests:
        - warn
    jest/no-focused-tests:
        - error

globals:
    container: true
