version: '3'
services:
  microservice:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/service/
      - /usr/src/service/node_modules
    environment:
      - POSTGRES_HOST=template-postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=template_db
    links:
      - template-postgres
    depends_on:
      - template-postgres

  template-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=template_db
    volumes:
      - template_postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5433

volumes:
  template_postgres_data:
