version: '3'
services:
  microservice:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - .:/usr/src/service/
      - /usr/src/service/node_modules
    environment:
      - MONGODB_HOST=mongodb
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
    ports:
        - 27017:27017

volumes:
  mongo-db:
  mongo-config:
